### ISSUE TITLE
antizuckbook.com not listed

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [Minoru/minoru-fediverse-crawler#191]
Our Friendica instance antizuckbook.com, first created nearly ~a year ago, is not listed. https://nodes.fediverse.party/nodes.json

**Comment by Minoru** [comment]
I just checked and I see it in the list:

```
$ jq . nodes.json | grep antizuckbook.com
  "antizuckbook.com",
```

I also see that the crawler visited the instance four times since June 5th. (I don't keep older logs.) So presumably it should have been in the list two hours ago, too. If you downloaded the JSON file and still have it, can you please double-check that the node is not in there? And if so, please show the file to me, perhaps it'll help me figure things out.

**Comment by DetroitLibertyPenguin** [comment]
> I just checked and I see it in the list:
> 
> ```
> $ jq . nodes.json | grep antizuckbook.com
>   "antizuckbook.com",
> ```
> 
> I also see that the crawler visited the instance four times since June 5th. (I don't keep older logs.) So presumably it should have been in the list two hours ago, too. If you downloaded the JSON file and still have it, can you please double-check that the node is not in there? And if so, please show the file to me, perhaps it'll help me figure things out.

Nope I didn't save it, but it's there now, so whatever. marked as closed
